name: Validate

on: 'push'

jobs:
  validate-build-ubuntu:
    name: Validate (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
        ~/.local/bin/conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        ~/.local/bin/conan profile new --detect default
        ~/.local/bin/conan profile update settings.compiler=clang default
        ~/.local/bin/conan profile update settings.compiler.version=9 default
        ~/.local/bin/conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Build
      run: |
        ~/.local/bin/conan create . Catch2/2.13.2@iceshard/stable
